apiVersion: apps/v1
kind: Deployment
metadata: 
  name: pulsedesk-worker

spec: 
  replicas: 1
  selector:
    matchLabels:
      app: pulsedesk-worker
  template:
      metadata:
        labels:
          app: pulsedesk-worker
      spec:
        containers:
        - name: pulsedesk-worker
          image: PLACEHOLDER
          env:
        - name: AWS_REGION
          value: "us-east-2"
        - name: QUEUE_URL 
          value: "PLACEHOLDER"
        - name: USERS_TABLE
          value: "PLACEHOLDER"
        - name: SENDER_EMAIL
          value: "PLACEHOLDER"
        - name: BEDROCK_MODEL_ID
          value: "PLACEHOLDER" 


